apiVersion: apps/v1

kind: Deployment

metadata:
  name: conversao-distancia

spec:
  replicas: 8
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
        - name: conversao-distancia
          image: kakoferrare/conversao-distancia:v1
          ports:
            - containerPort: 5000
          #resources:
          #  requests:
          #    memory: "128Mi"
          #    cpu: "500m"
          #  limits:
          #    memory: "256Mi"
          #    cpu: "1"

---
apiVersion: v1

kind: Service

metadata:
  name: conversao-distancia

spec:
  selector:
    app: conversao-distancia
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
